### ISSUE TITLE
Questions about the implementation of NOSE

### ISSUE THREAD

**Issue by exhyy** [sihaoevery/lambda_vit#4]
Hi, thanks for your great work!

I am confused about some implementation details of NOSE:
1. Is NOSE a phase that is completely independent of model training?
2. Is the calculation of transfer entropy performed on the pre-trained DeiT, or is it done with random initialized ones?

**Comment by sihaoevery** [comment]
Hi exhyy,

1. Yes and No. In ImageNet, we use the training data to calculate the NOSE. So it is not independent from model training. For CIFAR and ADE20k, we use the searched layers from ImageNet for model training. In this case, you can say NOSE is independent from model training.

2. Yes. We use the pre-trained model to compute transfer entropy in one-shot manner.

Regards,

Sihao

**Comment by exhyy** [comment]
I see. Thanks for your detailed explanation!
